# permissions for end users to view userdefinednetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kustomize
  name: userdefinednetwork-viewer-role
rules:
- apiGroups:
  - selfservice.cnv
  resources:
  - userdefinednetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - selfservice.cnv
  resources:
  - userdefinednetworks/status
  verbs:
  - get
