# permissions for end users to edit userdefinednetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: network-self-service
    app.kubernetes.io/managed-by: kustomize
  name: userdefinednetwork-editor-role
rules:
- apiGroups:
  - selfservice.cnv
  resources:
  - userdefinednetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selfservice.cnv
  resources:
  - userdefinednetworks/status
  verbs:
  - get
