name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  K8S_VERSION: v1.29.2
  OCI_BIN: docker
  CLUSTER_NAME: test

jobs:
  build-lint-unit-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: make

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.57.2
        args: --timeout 3m --verbose cmd/... internal/...

    - name: Unit test
      run: make test

  e2e:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Start cluster
      timeout-minutes: 30
      env:
        KIND_ALLOW_SYSTEM_WRITES: true
      run: make cluster-up

    - name: Sync cluster (build & push image, install CRD, deploy controller)
      timeout-minutes: 30
      run: make cluster-sync

    - name: Run e2e tests
      timeout-minutes: 30
      env:
        KIND_CLUSTER: ${{ env.CLUSTER_NAME }}
      run:  make test-e2e

    - name: Delete cluster
      run: make cluster-down
